openapi: 3.0.1
tags:
- name: Skill Repetition
  description: APIs for managing skill repetition
paths:
  /v0/repeat/{id}:
    post:
      tags:
      - Skill Repetition
      summary: Mark a skill as repeated
      description: Records a repetition of a skill and updates its repetition history
      operationId: repeat
      parameters:
      - name: id
        in: path
        description: ID of the skill to mark as repeated
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Successfully recorded skill repetition
